name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Init/Plan/Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/main_infrastructure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Write backend config
        run: echo "${{ secrets.TF_BACKEND_HCL }}" > backend.hcl

      - name: Write tfvars file
        run: echo "${{ secrets.TF_VARS }}" > personal.auto.tfvars

      - name: Write Yandex Cloud SA key        
        run: |
          cat <<EOF > key.json
          ${{ secrets.YC_SA_KEY }}
          EOF

    #   - name: Terraform Init
    #     run: terraform init -backend-config=backend.hcl

    #   - name: Terraform Validate
    #     run: terraform validate

    #   - name: Terraform Plan
    #     run: terraform plan -out=tfplan -var-file=personal.auto.tfvars

    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve tfplan
